CREATE TABLE users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    
    username VARCHAR(30) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    
    rating INT DEFAULT 1000,
    rank ENUM('BRONZE','SILVER','GOLD','DIAMOND') DEFAULT 'BRONZE',
    
    wallet_balance DECIMAL(10,2) DEFAULT 0.00,
    
    is_verified BOOLEAN DEFAULT FALSE,
    is_banned BOOLEAN DEFAULT FALSE,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);